config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :likes, only: [:create]
    collection do
      get "feed"
    end
  end
  root "posts#index"

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      post "follow", to: "follows#create"
      delete "unfollow", to: "follows#destroy"
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  get "search", to: "search#index", as: "search"
  get "admin/dashboard", to: "admin#dashboard", as: "admin_dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"
  belongs_to :followed, class_name: "User", foreign_key: "followed_id"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :likers, through: :likes, source: :user
  has_one_attached :image

  validates :title, presence: true
  validates :description, length: { maximum: 140, message: "must be 140 characters or less" }, allow_blank: true
  validates :image, presence: { message: "must be uploaded" }

  LICENSES = ["Copyright", "Free Art License", "CC BY", "CC BY-SA", "CC BY-NC", "CC BY-NC-SA", "CC BY-ND", "CC BY NC-ND", "CC0"]
  validates :license, inclusion: { in: LICENSES }

  def self.search(keyword)
    return Post.none if keyword.blank?

    where("LOWER(title) LIKE ?", "%#{keyword.downcase}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post

  # Users that this user is following
  has_many :follows, foreign_key: :follower_id, dependent: :destroy
  has_many :followed_users, through: :follows, source: :followed

  # Users that are following this user
  has_many :reverse_follows, class_name: "Follow", foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :reverse_follows, source: :follower

  has_one_attached :profile_picture
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.admin ||= false
  end

  def admin?
    self.admin
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :ensure_admin

  def dashboard
  end

  private

  def ensure_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  helper_method :current_user, :logged_in?, :admin_user?

  def current_user
    # If session[:user_id] is nil, set it to nil, otherwise find the user by id.
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def admin_user?
    logged_in? && current_user.admin?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  before_action :find_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to @post
    else
      render "edit"
    end
  end

  def destroy
    @comment.destroy
    redirect_to @post
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = @post.comments.find(comment_params)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    @user = User.find(params[:id])
    current_user.followed_users << @user unless current_user.followed_users.include?(@user)
    redirect_to @user
  end

  def destroy
    @user = User.find(params[:id])
    current_user.followed_users.delete(@user)
    redirect_to @user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.find_or_initialize_by(user: current_user)

    if @like.new_record?
      @like.save
    else
      @like.destroy
    end

    redirect_to params[:redirect_to] || posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = fetch_posts
  end

  def feed
    @posts = Post.where(user_id: current_user.followed_users.pluck(:id)).order("created_at DESC")
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, status: :see_other
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def fetch_posts
      posts = Post.all.order("created_at DESC")
      if params[:search].present?
        posts.where("description LIKE ?", "%#{params[:search]}%")
      else
        posts
      end
    end

    def post_params
      params.require(:post).permit(:title, :description, :image, :license)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].present?
      @posts = Post.search(params[:query]).order("created_at DESC")
    else
      @posts = Post.none
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def show
    @posts = @user.posts.order("created_at DESC")
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User created successfully"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params_edit)
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def user_params_edit
    params.require(:user).permit(:profile_picture, :username, :bio, :email, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def find_hashtags(text)
    results = text.scan(/#\w+/)
    results.each do |result|
      result_link = link_to result, posts_path(search: result)
      text.gsub!(result, result_link)
    end
    text
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<strong class="comment-user-link"><%= link_to comment.user.username, user_path(comment.user)  %>: </strong>
<p><%= comment.content %></p>

app/views/comments/_form.html.erb
<%= form_with model: [@post, @comment] do |form| %>
  <div>
    <%= form.text_area :content, class: "form-control comment-input", placeholder: "Add a comment..." %>
  </div>
  <div>
    <%= form.submit 'Post Comment', class: "btn btn-outline-secondary btn-sm mt-2 post-comment-btn" %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<div class="container mt-4 d-flex justify-content-center">
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title mb-4">Create a Post</h5>
        <%= form_with model: @post, html: { id: 'postForm' } do |form| %>

          <% if @post.errors.any? %>
            <div class="alert alert-danger text-center">
              <% @post.errors.full_messages.each do |message| %>
                <div><%= message %></div>
              <% end %>
            </div>
          <% end %>

          <div class="mb-3">
            <%= form.label :title, class: 'form-label' %><br>
            <%= form.text_field :title, class: "form-control" %>
          </div>

          <div class="mb-3">
            <%= form.label :image, class: "form-label" %>
            <%= form.file_field :image, class: "form-control", id: "postImage", accept: ".png, .jpg, .jpeg" %>
          </div>

          <div class="mb-3">
            <%= form.label :license, class: "form-label" %>
            <%= form.select :license, Post::LICENSES, prompt: "Select A License", selected: "Copyright", class: "form-select" %>
          </div>

          <div id="postTextContainer" class="mb-3">
            <%= form.label :description, class: "form-label" %>
            <%= form.text_area :description, maxlength: 140, id: "postText", class: "form-control", rows: "3" %>
          </div>

          <div class="mb-3">
            <img id="imagePreview" src="#" alt="Image Preview" style="display: none; max-width: 100%; height: auto;" />
          </div>

          <div>
            <%= form.submit class: "btn btn-primary" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container mt-4 d-flex justify-content-center">
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title mb-4">Edit your Post</h5>
        <%= form_with model: @post, html: { id: 'postForm' } do |form| %>

          <% if @post.errors.any? %>
            <div class="alert alert-danger text-center">
              <% @post.errors.full_messages.each do |message| %>
                <div><%= message %></div>
              <% end %>
            </div>
          <% end %>

          <div class="mb-3">
            <%= form.label :title, class: 'form-label' %><br>
            <%= form.text_field :title, class: "form-control" %>
          </div>

          <div class="mb-3">
            <%= form.label :image, class: "form-label" %>
            <%= form.file_field :image, class: "form-control", id: "postImage", accept: ".png, .jpg, .jpeg" %>
          </div>

          <div id="postTextContainer" class="mb-3">
            <%= form.label :description, class: "form-label" %>
            <%= form.text_area :description, maxlength: 140, id: "postText", class: "form-control", rows: "3" %>
          </div>

          <div class="mb-3">
            <img id="imagePreview" src="#" alt="Image Preview" style="display: none; max-width: 100%; height: auto;" />
          </div>

          <div>
            <%= form.submit class: "btn btn-primary" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/feed.html.erb
<div class="container mt-4 d-flex justify-content-center">
  <div class="col-md-8">
    <div id="postContainer">
      <% @posts.each do |post| %>
        <div class="card post-card">
          <div class="card-body">
            <div class="d-flex align-items-start">
              <% if post.user.profile_picture.attached? %>
                <%= image_tag(post.user.profile_picture, class: 'profile-picture-index me-3')%>
              <% else %>
                <%= image_tag('default_profile_picture.png', class: 'profile-picture-index me-3') %>
              <%end%>
              <div>
                <h5 class="card-title"><%= link_to post.user.username, user_path(post.user) %></h5>
                <p class="post-caption"><%= post.title %></p>
              </div>
            </div>
            <div> <%= link_to image_tag(post.image, class: 'img-fluid post-image-index mt-3'), post_path(post) %></div>
            <div class="d-flex justify-content-between mt-3">
              <div class="d-flex align-items-center">
                <span class="ms-2" id="like-count-<%= post.id %>"><%= post.likes.count %> likes</span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <% if @posts.empty?%>
        <p class="post-caption text-white text-center">There's no posts from the people you follow. Maybe follow some more artists?</p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container mt-4 d-flex justify-content-center">
  <div class="col-md-8">
    <div id="postContainer">
      <% @posts.each do |post| %>
        <div class="card post-card">
          <div class="card-body">
            <div class="d-flex align-items-start">
              <% if post.user.profile_picture.attached? %>
                <%= image_tag(post.user.profile_picture, class: 'profile-picture-index me-3')%>
              <% else %>
                <%= image_tag('default_profile_picture.png', class: 'profile-picture-index me-3') %>
              <%end%>
              <div>
                <h5 class="card-title"><%= link_to post.user.username, user_path(post.user) %></h5>
                <p class="post-caption"><%= post.title %></p>
              </div>
            </div>
            <div> <%= link_to image_tag(post.image, class: 'img-fluid post-image-index mt-3'), post_path(post) %></div>
            <div class="d-flex justify-content-between mt-3">
              <div class="d-flex align-items-center">
                <span class="ms-2" id="like-count-<%= post.id %>"><%= post.likes.count %> likes</span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container mt-4 d-flex justify-content-center">
  <div class="col-md-8">
    <div id="postContainer">
      <div class="card post-card">
        <div class="card-body">
          <div class="d-flex align-items-start">
            <% if @post.user.profile_picture.attached? %>
              <%= image_tag(@post.user.profile_picture, class: 'profile-picture-index me-3')%>
            <% else %>
              <%= image_tag('default_profile_picture.png', class: 'profile-picture-index me-3') %>
            <%end%>
            <div>
              <h5 class="card-title"><%= link_to @post.user.username, user_path(@post.user) %></h5>
              <p class="post-caption"> <%= @post.title %></p>
            </div>
          </div>
          <div> <%= link_to image_tag(@post.image, class: 'img-fluid post-image-show mt-3'), post_path(@post) %></div>
          <div class="my-3">
            <strong class="post-caption"> Posted <%= time_ago_in_words(@post.created_at)%> ago</strong>
            <p><%= simple_format(find_hashtags(@post.description)) %> </p>
          </div>
          <div class="my-3">  <strong>License:</strong> <%= @post.license %></div>
          <div class="d-flex justify-content-between mt-3">
            <div class="d-flex align-items-center">
              <% if logged_in? %>
                <%= form_with(url: post_likes_path(@post, redirect_to: post_path(@post)), method: :post, local: true) do %>
                  <%= button_tag class: 'btn btn-outline-primary btn-md like-btn btn-icon like-button' do %>
                    <i class="fas fa-thumbs-<%= @post.likers.include?(current_user) ? 'down' : 'up' %>"></i>
                  <% end %>
                <% end %>
              <% end %>
              <span class="ms-2" id="like-count-<%= @post.id %>"><%= @post.likes.count %> likes</span>
            </div>
            <% if logged_in? %>
            <% if admin_user? || @post.user == current_user %>
              <div class="d-flex">
                <button class="btn btn-outline-secondary btn-md edit-caption-btn btn-icon me-2">
                  <%= link_to raw("<i class='fas fa-pencil-alt'></i>"), edit_post_path(@post) %>
                </button>
                <button class="btn btn-outline-danger btn-md delete-btn btn-icon">
                  <%= link_to raw("<i class='fas fa-trash'></i>"), post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete your post?" } %>
                </button>
              </div>
            <% end %>
            <% end %>
          </div>
          <div class="comment-section mt-3">
            <% if logged_in? %>
              <%= render 'comments/form' %>
            <% end %>
            <div class="comments-list mt-2">
              <%= render @post.comments, class: "comment" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="container mt-5 d-flex justify-content-center">
  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title text-center mb-4">Create Your Account</h3>
          <%= form_with model: @user, html: { class: 'createAccountForm' } do |form| %>

            <% if @user.errors.any? %>
              <div class="alert alert-danger text-center">
                <% @user.errors.full_messages.each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>
            <% end %>

            <div class="mb-3">
              <%= form.label :username, class: 'form-label' %><br>
              <%= form.text_field :username, class: 'form-control', placeholder: 'Create a username' %>
            </div>

            <div class="mb-3">
              <%= form.label :email, class: 'form-label' %><br>
              <%= form.text_field :email, class: 'form-control', placeholder: 'Enter your email' %>
            </div>

            <div class="mb-3">
              <%= form.label :password, class: 'form-label' %><br>
              <%= form.password_field :password, class: 'form-control', placeholder: 'Create your password' %>
            </div>

            <div class="mb-3">
              <%= form.label :password_confirmation, class: 'form-label' %><br>
              <%= form.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm your password' %>
            </div>

            <div class="d-grid">
              <%= form.submit 'Create Account', class:'btn btn-primary' %>
            </div>

          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="container mt-5 pt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h3 class="text-white text-center mb-4">Edit Profile</h3>
      <%= form_with(model: @user, local: true) do |form| %>
        <div class="mb-3 text-white text-center">
          <% if @user.profile_picture.attached? %>
            <%= image_tag(@user.profile_picture, class: 'profile-picture-show mb-4')%>
          <% else %>
            <%= image_tag('default_profile_picture.png', class: 'profile-picture-show mb-4') %>
          <%end%>
          <%= form.file_field :profile_picture, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :username, class: "form-label text-white" %>
          <%= form.text_field :username, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :bio, class: "form-label text-white" %>
          <%= form.text_area :bio, class: "form-control", rows: 3 %>
        </div>
        <div class="mb-3">
          <%= form.label :email, class: "form-label text-white" %>
          <%= form.text_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :password, class: "form-label text-white" %>
          <%= form.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :password_confirmation, class: "form-label text-white" %>
          <%= form.password_field :password_confirmation, class: "form-control" %>
        </div>
        <div class="d-grid">
          <%= form.submit "Save Changes", class:'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5 pt-4">
  <div class="row">
    <div class="col-md-4 text-center text-white">
      <div class="mb-4">
        <% if @user.profile_picture.attached? %>
            <%= image_tag(@user.profile_picture, class: 'profile-picture-show')%>
          <% else %>
            <%= image_tag('default_profile_picture.png', class: 'profile-picture-show') %>
          <%end%>
      </div>
      <h3> <%=@user.username%> </h3>
      <p class="user-bio">
        <%= @user.bio.present? ? @user.bio : "This user has not set a bio yet." %>
      </p>
      <% if logged_in? %>
        <% if @user == current_user %>
          <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-secondary" %>
          <% else %>
            <% if current_user.followed_users.include?(@user) %>
              <%= button_to 'Unfollow', unfollow_user_path(@user), method: :delete, class: "btn btn-secondary" %>
            <% else %>
              <%= button_to 'Follow', follow_user_path(@user), method: :post, class: "btn btn-secondary" %>
            <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-8">
      <div id="postContainer">
        <% @posts.each do |post| %>
          <div class="card post-card">
            <div class="card-body">
              <div class="d-flex align-items-start">
                <div>
                  <h4 class="card-title"><%= post.title %></h4>
                  <p class="post-caption"> <%= post.user.username %></p>
                </div>
              </div>
              <div> <%= link_to image_tag(post.image, class: 'img-fluid post-image-index mt-3'), post_path(post) %></div>
              <div class="my-3">
                <strong class="post-caption"> Posted <%= time_ago_in_words(post.created_at)%> ago</strong>
                <p><%= simple_format(find_hashtags(post.description)) %> </p>
              </div>
              <div class="d-flex justify-content-between mt-3">
                <div class="d-flex align-items-center">
                  <span class="ms-2" id="like-count-<%= post.id %>"><%= post.likes.count %> likes</span>
                </div>
                <% if logged_in? %>
                <% if admin_user? || @user == current_user %>
                  <div class="d-flex">
                    <button class="btn btn-outline-secondary btn-md edit-caption-btn btn-icon me-2">
                      <%= link_to raw("<i class='fas fa-pencil-alt'></i>"), edit_post_path(post) %>
                    </button>
                    <button class="btn btn-outline-danger btn-md delete-btn btn-icon">
                      <%= link_to raw("<i class='fas fa-trash'></i>"), post_path(post), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete your post?" } %>
                    </button>
                  </div>
                <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        <% if @posts.empty? %>
          <p class="post-caption text-white text-center">This user has not posted anything yet.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>