config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :likes, only: [:create]
    collection do
      get "feed"
    end
  end
  root "posts#index"

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      post "follow", to: "follows#create"
      delete "unfollow", to: "follows#destroy"
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  get "search", to: "search#index", as: "search"
  get "admin/dashboard", to: "admin#dashboard", as: "admin_dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"
  belongs_to :followed, class_name: "User", foreign_key: "followed_id"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :likers, through: :likes, source: :user
  has_one_attached :image

  validates :title, presence: true
  validates :description, length: { maximum: 140, message: "must be 140 characters or less" }, allow_blank: true
  validates :image, presence: { message: "must be uploaded" }

  LICENSES = ["Copyright", "Free Art License", "CC BY", "CC BY-SA", "CC BY-NC", "CC BY-NC-SA", "CC BY-ND", "CC BY NC-ND", "CC0"]
  validates :license, inclusion: { in: LICENSES }

  def self.search(keyword)
    return Post.none if keyword.blank?

    where("LOWER(title) LIKE ?", "%#{keyword.downcase}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post

  # Users that this user is following
  has_many :follows, foreign_key: :follower_id, dependent: :destroy
  has_many :followed_users, through: :follows, source: :followed

  # Users that are following this user
  has_many :reverse_follows, class_name: "Follow", foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :reverse_follows, source: :follower

  has_one_attached :profile_picture
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.admin ||= false
  end

  def admin?
    self.admin
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :ensure_admin

  def dashboard
  end

  private

  def ensure_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.find_or_initialize_by(user: current_user)

    if @like.new_record?
      @like.save
    else
      @like.destroy
    end

    redirect_to params[:redirect_to] || posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = fetch_posts
  end

  def feed
    @posts = Post.where(user_id: current_user.followed_users.pluck(:id)).order("created_at DESC")
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, status: :see_other
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def fetch_posts
      posts = Post.all.order("created_at DESC")
      if params[:search].present?
        posts.where("description LIKE ?", "%#{params[:search]}%")
      else
        posts
      end
    end

    def post_params
      params.require(:post).permit(:title, :description, :image, :license)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].present?
      @posts = Post.search(params[:query]).order("created_at DESC")
    else
      @posts = Post.none
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def show
    @posts = @user.posts.order("created_at DESC")
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User created successfully"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params_edit)
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def user_params_edit
    params.require(:user).permit(:profile_picture, :username, :bio, :email, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def find_hashtags(text)
    results = text.scan(/#\w+/)
    results.each do |result|
      result_link = link_to result, posts_path(search: result)
      text.gsub!(result, result_link)
    end
    text
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard.html.erb
<div class="text-white text-center">
  <h1>Welcome to your dashboard</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Aurora" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light custom-navbar fixed-top">
      <div class="container-fluid">
          <div class="navbar-brand custom-navbar-title fw-bold">Aurora</div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <%= link_to 'Home', root_path, class: 'nav-link custom-nav-item' %>
              </li>
              <% if logged_in?%>
                <li class="nav-item">
                  <%= link_to 'Profile', user_path(current_user), class: 'nav-link custom-nav-item'%>
                </li>
                <li class="nav-item">
                  <%= link_to 'Feed', feed_posts_path, class: 'nav-link custom-nav-item'%>
                </li>
              <% end %>
            </ul>

            <%= form_with(url: search_path, method: :get, local: true, class: "d-flex position-absolute top-50 start-50 translate-middle") do %>
              <%= text_field_tag :query, params[:query], class: "form-control me-2", placeholder: "Search" %>
              <%= submit_tag "Search", class: "btn btn-secondary" %>
            <% end %>

            <ul class="navbar-nav ms-auto">
              <% if logged_in? %>
                <li class="nav-item" id="welcomeItem">
                  <span class="nav-link custom-nav-item">Hello, <%= current_user.username %>!</span>
                </li>
                 <li class="nav-item" id="uploadPostItem">
                  <%= link_to 'New Post', new_post_path, class: 'nav-link custom-nav-item' %>
                </li>
                <li class="nav-item" id="logoutItem">
                  <%= link_to 'Log out', user_session_path(current_user), class: 'nav-link custom-nav-item', data: { turbo_method: :delete } %>
                </li>
              <% else %>
                <li class="nav-item" id="signInItem">
                  <%= link_to 'Sign In', new_user_session_path, class: 'nav-link custom-nav-item' %>
                </li>
                <li class="nav-item" id="createAccountItem">
                  <%= link_to 'Create Account', new_user_path, class: 'nav-link custom-nav-item' %>
                </li>
              <% end %>
            </ul>
          </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>